services:
  - type: web
    name: pharmacare-api
    runtime: docker
    rootDir: BACKEND
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: GOOGLE_WEB_CLIENT_ID
        value: 285680876693-fmqubravnj1d5hoh5aseovjetem74tlm.apps.googleusercontent.com
      - key: GOOGLE_ANDROID_CLIENT_ID
        sync: false
